name: dial_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_keyboard_visibility: ^6.0.0
  path_provider: ^2.1.3
  path: ^1.9.0
  chat_bubbles: ^1.6.0
  pin_code_fields: ^8.0.1
  change_app_package_name: ^1.2.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  country_pickers: ^3.0.1
  country_code_picker: ^3.0.0
  image_picker: ^1.1.2
  firebase_storage: ^12.0.0
  permission_handler: ^11.3.1
  contacts_service: ^0.6.3
  firebase_messaging: ^15.0.0
  shared_preferences: ^2.2.3
  flutter_firebase_chat_core: ^1.6.8
  flutter_local_notifications: ^17.1.2
  flutter_webrtc: ^0.11.1
  socket_io_client: ^3.0.0-beta.2
  http: ^1.2.1
  audioplayers: ^6.0.0
  awesome_notifications: ^0.9.3+1

dev_dependencies:
  flutter_lints: ^4.0.0
  rename: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
  assets:
    - assets/svg/
    - assets/ringtone.mp3
